{{- if not .Values.datadog.highAvailability.failoverApiKeyExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "datadog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "datadog.labels" . | indent 4 }}
{{- if .Values.datadog.secretAnnotations }}
  annotations: {{ toYaml .Values.datadog.secretAnnotations | nindent 4 }}
{{- end }}
type: Opaque
data:
  api-key: {{ default "MISSING" .Values.datadog.highAvailability.failoverApiKey | b64enc | quote }}
{{- end }}
